filter:
  paths: [src/*]
  excluded_paths: [vendor/*, test/*]
before_commands:
  - 'composer install --dev --prefer-source'
checks:
  php:
    code_rating: true
    duplication: true
build:
  environment:
    php:
      version: 7.1
